version: '2'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: registry.gitlab.com/luxonis/blobconverter/api
    environment:
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
    ports:
      - 8080:8080