version: '2'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: registry.gitlab.com/luxonis/blobconverter/api
    environment:
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
  nginx:
    build: ./nginx
    ports:
      - 880:80
      - 8443:443
    depends_on:
      - api
    volumes:
      - ./log:/log:z
      - /etc/letsencrypt/archive/blobconverter.luxonis.com/privkey2.pem:/ssl/key.pem
      - /etc/letsencrypt/archive/blobconverter.luxonis.com/fullchain2.pem:/ssl/cert.pem
